language: node_js
nodejs:
- 10

addons:
  snaps:
  - name: snapcraft
    channel: stable
    confinement: classic

branches:
  only:
  - develop
  - /^release\/.*/
  - master

script:
- npm run ci

deploy:
  channel: candidate
  provider: snap
  skip-cleanup: true
  snap: ./dist/net-worth_*.snap
  on:
    branch: master

notifications:
  email:
    recipients:
    - secure: NE5+w2yIOCpJpxtWlXmudHn43QPrIhimwXXyMalHnCQ9HLmBqbpICO/p6Sm1Zh5b4GhkhgNohrdL03cf5GBKXb3ZRUZTRUan6tGLqFw2KEjv6FhXSTUn3RzYuzac8PjbnrIzg0yUfiCQkdZATpLiTYsfJdFRicqSJu9UlcfsgeiaFHavbzoH0VoNSAlMnn1LvVqz8Wi0B6xbbudlEoDFTQG875bdMIL/uNcwIbBI/4VK+d7wnhjiAJcNdPDbqRvhzW6GXXCNcvNzPZjNVEMLZRhjTqm/KJirePZRhATxxvCMODu73vA6H2pxYi3XxOrtjG9bY/YJAqYmqsrt+bpbPC7IaU1jjwxsjrVEH+UJTmcKDhvCk4CqE66xmpVsw3q568alTktFTfL3LLdWzAG1BkeXh43T6SyRjLgKDEF34owr88X/8fgBYockzxMv3qa6aes8U7xJz4s53qvssOrjO/U+WtjEIPPWIjJ2txeYHWicErG4sdWPe4NtlaTH/PKJRUoh+HZC+Q5ie4VR4CuYkRfcThxQrbSNRKUVQA/7X82uMI/g7HDereUFWiyLk6X6aqbeqTi4MO2yEuF4bqSgyQszLaxotogr9tv9/P2tQmMBg75OfTlGsFkhP8OZDuj7S8zyKJ/09TOidAGa8PWvmNj5fYL93KnGba4ey05nE+w=
