name: net-worth
version: '1.0.0'
summary: Provides an overview of your precious metal and crypto assets.
description: |
  If you primarily store your wealth in 'unconventional' assets like precious metals and crypto currencies, it seems
  difficult to get an overview of your current financial situation.
  
  Net Worth aims to make this a little easier. In a nutshell, the application presents your precious metal and crypto
  currency holdings in a groupable and sortable table, which allows you to quickly see how your net worth is spread
  among the different asset types and locations.

grade: devel
confinement: devmode

apps:
  net-worth:
    command: net-worth

parts:
  net-worth:
    plugin: nodejs
    source: .
    npm-run: [ dist ]
